### PR TITLE
FAQ Update - Add mentor request question

### PR DESCRIPTION
**Pull request by soris-codes**
# Description of changes
Added mentor question to FAQ's including `/mentor` command in Slack channels to fill out form.

### CODE REVIEW

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit f439aa3fbce341e53a63190d323d130bbfcb16d9

https://deploy-preview-633--operation-code-storybook.netlify.com

**Comment by kylemh** [comment]
@soris-codes sorry we don't use npm here! Can you please remove your changes to `package.json` and remove uncommit the `package-lock.json` file?

**Comment by soris-codes** [comment]
> @soris-codes sorry we don't use npm here! Can you please remove your changes to `package.json` and remove uncommit the `package-lock.json` file?

Sorry about that! I didn't have yarn on my machine till today. Thanks for the opportunity to learn.

**Comment by kylemh** [comment]
@soris-codes no problem at all! You're one of many to do something with `npm`, so it's an opportunity for us to improve! [Updated documentation to try avoiding this in the future](https://github.com/OperationCode/front-end/commit/de58006ae980a2407299efb4cff5bd54e5785a49).

**Comment by kylemh** [comment]
I'll update prod later tonight. You should see your change live tomorrow.

**Pull request merged**
