### PR TITLE
Implement newly-designed /events page (issue #166)

### LINKED ISSUE #166: Create /events page
# Feature
## Why is this feature being added?

Our design team has come up with a beautiful redesign to simplify UX.

## What should your feature do?
Implement the newly-designed landing page via `pages/events.js`
Here is the mock-up: https://invis.io/KSO12EFRU7E#/323662230_OC_Events_Landing_Page

## Temporary Note
This project requires back-end labor to finish (creating events surrounding our meetup groups and events). In the meantime, you can act upon a JSON of you shape/choosing in order to mock the data represented in the design mock.

### PR DESCRIPTION
**Pull request by lineberry30**
# Description of changes
- Updating the 'get-involved' page to match the mockups (https://projects.invisionapp.com/share/GRO3FKUEZMX#/screens/320139024).

# Issue Resolved
Resolves #166 

There are still some issues that need to be addressed:
- fonts
- colors
- minor spacing issues (dependent on fonts)
- slack form submission currently goes nowhere
- the donation progress bar needs to hooked up to some % remaining logic

### CODE REVIEW

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit e6e978a4f6ab6f9264fcc72de669d9cb8f2d4244

https://deploy-preview-234--operation-code-storybook.netlify.com

**Comment by lineberry30** [comment]
Just realized I forgot to update the offset images like the mocks show. I'm going to close for now and reopen when I have that implemented.

**Comment by lineberry30** [comment]
Thanks @sethbergman @kylemh!

**Comment by kylemh** [comment]
@lineberry30 nope! Laura gave me the `.png` files, but I havent had a moment to convert them to SVGs yet. The two I didn't provide weren't symmetrical so they require a bit more effort to trace about.

**Pull request merged**
