### PR TITLE
Scroll-up-button

### PR DESCRIPTION
**Pull request by dirtyredz**
# Description of changes
Adds scroll up button functionality. Same package (updated) used in older website.

### CODE REVIEW

**Comment by dirtyredz** [comment]
I should have read the other PR's formTextArea was already taken care of. At least you can use the scroll up button.

**Comment by kylemh** [comment]
My thoughts exactly 😁 - will merge this ASAP

**Comment by dirtyredz** [comment]
There are also other button styles to choose from if the default doesn't work with the current design theme:
https://react-scroll-up-button.com

**Comment by dirtyredz** [comment]
Removed the extra tests commit from this pr

**Pull request merged**
