### PR TITLE
Donate Page "Why Donate?"

### PR DESCRIPTION
**Pull request by alexzw7**
# Description of changes

Added a "Why Donate?" section before the donation form of the donate page.
# Issue Resolved

Addresses #1418 
## Screenshots/GIFs

Screen Shot 2021-04-26 at 4 08 27 PM

### CODE REVIEW

**Review by datphotogurl — CHANGES_REQUESTED** [review]
Please change the copy to: 
<h1>Why Donate?</h1>
          <p>
            Operation Code runs all operations and programs based on donations. We need your help!  Your donations go directly towards helping our members by maintaining our open source software and infrastructure where an immersive learning environment helps members grow their skills while contributing to code repositories. We also provide free learning licenses, develop hiring pipelines, and provide professional training and development for mentors and volunteers. 
</p>
<p>
        Your donations also helps our community reduce the risk facing our transitioning military, military spouses and military veterans by growing social connectedness, building camaraderie and teaching tangible technical and personal skills that combat chronic unemployment, homelessness, and suicide. You're providing members with the opportunity to learn software development, enter the tech industry, and Deploy The Future!
          </p>
          <p>
            As the largest community of military veterans, service members, and military families, we are over 8000 strong and have both the technical and military transitioning experience and helped thousands of members enter into the tech occupation and industry. As we continue to grow at an average rate of 33% annually, we cannot reach our mission to help our military community without your help!
          </p>
          <p>
            We pride ourselves in transparency, making sure that our community knows what their
            contributions are going towards, which has led to us receive the
            Gold Seal of Transparency from GuideStar in 2021. Feel free to reach out to us at staff@operationcode.org if you have any questions.

**Comment by alexzw7** [comment]
@datphotogurl Just updated and pushed the new copy text, with updated screenshot.

**Review by kylemh — APPROVED** [review]

**Comment by kylemh** [comment]
Will merge on you approval @datphotogurl

**Comment by datphotogurl** [comment]
Nice! @kylemh the updates are now approved. Merge can be completed.

**Pull request merged**
