### PR TITLE
Save docker images in ECR

### PR DESCRIPTION
**Pull request by wimo7083**
# Description of changes

This will start saving the docker images and build the k8s configs.

### CODE REVIEW

**Comment by wimo7083** [comment]
The more I read about this, I think it's going to be better to get it into docker_hub.

**Comment by kylemh** [comment]
Updated documentation and got ride of the node_js flag. The build is failing saying incompatible version of node. Why would it be using 8.9.3? I think something in CI is choosing it for us.

**Comment by wimo7083** [comment]
Still deciding if I'm going to use ECR or dockerhub for all. Either way I'm waiting on some assistance with credentials.

**Comment by wimo7083** [comment]
Per Kyle's request this is no longer needed.

**Comment by ohaiwalt** [comment]
you closed it right about when I fixed the problem :shakes_fist:

**Comment by ohaiwalt** [comment]
https://github.com/OperationCode/operationcode_infra/issues/64

**Pull request closed without merging**
