### PR TITLE
Migrated to latest Storybook

### LINKED ISSUE #397: Migrate to newest version of Storybook
# Feature request
**Is your feature request related to a problem? Please describe.**
#247 has been open for a long time.

**Describe the solution you'd like**
Bump Storybook and relevant add-ons to latest version and resolve any bugs that show up in `yarn storybook` and `yarn build-storybook`. Change whatever is needed to get it to work again!

### PR DESCRIPTION
**Pull request by KrDimitrov**
# Description of changes
Updates storybook and all its addons. 
Stories have also been migrated to CSF. 

# Issue Resolved

Fixes #397

### CODE REVIEW

**Comment by kylemh** [comment]
Seems like the deployment to Netlify timed out.

Is `yarn storybook:build` working for you locally? Immense work converting us to CSF btw 🎉 !

**Comment by KrDimitrov** [comment]
`yarn storybook:build` runs fine. There are a couple warnings about performance (bundle sizes), but it was done in 33s.

**Comment by kylemh** [comment]
Wonder why Netlify would be failing 🤔

**Comment by KrDimitrov** [comment]
Also tried building on my laptop. It took quite a bit longer,190s (manager build: 1.3min, prewiev build 1.6min) but still works. My laptop is kinda old though. 🤷‍♂️

**Comment by KrDimitrov** [comment]
There's an error in the logs...
```
1:15:08 AM:  Module not found: Error: Can't resolve 'fs' in '/opt/build/repo/node_modules/require-context.macro'
1:15:08 AM: (node:1368) UnhandledPromiseRejectionWarning: ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/opt/build/repo/node_modules/require-context.macro'
```
Maybe its related?

**Comment by KrDimitrov** [comment]
Alright. Let me know if I can help with something!

**Comment by kylemh** [comment]
I'm online. We can chat on Slack and figure this out maybe?

**Comment by KrDimitrov** [comment]
Yeah, I'm at school right now 😬so that's not really an option, sadly. I'll see to it when I get home

**Comment by kylemh** [comment]
Ah cool - no worries. I'll leave notes about my investigation

**Comment by kylemh** [comment]
Took a few ideas to heart with:

- Moving dependencies to prod (although this work made me realize I can move all of the Storybook dependencies back OUT of prod deps - we just did this before because of some no-longer-existant constraint)
- I noticed that the way you were loading stories didnt match the expressed documentation for Storyshots, but changing that actually completely broke Storybook
- After this, I created a minimum viable reproduction with https://github.com/kylemh/test-storyshots and shared it with the gurus in the Storybook team.

I'm gonna head to bed and hope for good news on Discord tomorrow 👍

**Comment by KrDimitrov** [comment]
>     I noticed that the way you were loading stories didnt match the expressed documentation
Got that from [here](https://github.com/storybookjs/storybook/blob/next/docs/src/pages/basics/writing-stories/index.md#loading-stories) and [here](https://github.com/storybookjs/storybook/issues/8080). 

I think its required to get CSF to work. I also used the macro to get storyshots to work, using `require.context` was the reason it was broken.

could the `fs` module issue be somehow related to [webpack](https://github.com/webpack-contrib/css-loader/issues/447)?

**Comment by kylemh** [comment]
Cool looks like we'll want to revert that change and also maybe need to update some file transforms!

https://github.com/storybookjs/storybook/tree/next/addons/storyshots/storyshots-core#multisnapshotwithoptionsoptions

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit c4425f711fb3462684d9feb565d25267d9d6c1f0

https://deploy-preview-886--operation-code-storybook.netlify.com

**Comment by KrDimitrov** [comment]
well now netlify builds, but the stories won't load. Locally, everything works.

**Comment by kylemh** [comment]
And snapshot tests aren't working - there's a lot to check off every time we take a whack at this unfortunately

**Comment by kylemh** [comment]
Resolved in #1132

I appreciate all the work you did @KrDimitrov because it undoubtedly helped @chynh get to the finish line!

**Pull request closed without merging**
