### PR TITLE
Feat/content container component

### LINKED ISSUE #306: Redefine Section component
# Feature request
**Is your feature request related to a problem? Please describe.**
Problem described in #294 

**Describe the solution you'd like**
There exist two components to be made:
1) A re-imagining of our `<Section>` component
 - has a gutter (max-width)
 - has themes to define background color
 - takes background-image (and related props) [see HeroBanner, and make HeroBanner a consumer of Section]
 - flex and flex-direction column with vertically and horizontally centered content
2) Some component (idk about name) which abstracts the behavior of sections in the redesign that have an image and some text. It should have a prop to the extent of `textPlacement="left" || textPlacement="right"` and the text alignment should be opposite its placement. On mobile, the image should always render first and the text should always be left aligned. This component will be consumed by the new Section component.

### PR DESCRIPTION
**Pull request by RaevLogic**
# Description of changes
This PR adds the ContentContainer, SectionContent, and HeroBanner components.

# Issue Resolved
Fixes #306 

## Screenshots/GIFs
N/A

### CODE REVIEW

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit 2f6aa4d55628f720240dc4c050ae16315d85c53b

https://deploy-preview-326--operation-code-storybook.netlify.com

**Comment by RaevLogic** [comment]
Travis is failing due to the old HeroBanner component still existing in the common component directory. I'm not sure what we're planning to do with the old component.

**Comment by kylemh** [comment]
Dont be alarmed. Pushed some progress work onto this branch cuz I'm turning in my work laptop tomorrow 😭

**Comment by kylemh** [comment]
screen shot 2019-02-23 at 4 46 16 pm

I am a terrible human being

**Pull request merged**
