### PR TITLE
refactoring footer styling

### PR DESCRIPTION
**Pull request by michaelDragomir**
# Description of changes
cleaning up the Footer styling.  Lots of odd shifting happening in responsive mode. off centered elements. reducing some of that css code. 

- replaced css file with tailwind and removed css
- fixed all styling issues 
- updated some logic to reduce complexity a bit.
-
BEFORE:
Screenshot 2024-06-06 at 9 55 43 AM

AFTER:
Screenshot 2024-06-06 at 9 57 28 AM

# Issue Resolved

Fixes #NA

### CODE REVIEW

**Comment by michaelDragomir** [comment]
THIS IS A WORK IN PROGRESS!

**Comment by michaelDragomir** [comment]
@kylemh THIS PR is ready for review. I've reduced the test failing to just one: **codeclimate/total-coverage**. didn't have much detail so not sure where the cause might be. Would love it if you put some eyes on that.

i've updated some logic and replaced that css file with tailwind. not sure what the protocol is for deleting css files which I did when switched to tailwind.

also, font sizes are a bit different from what's on production. 

comments welcome! :) thanks man...

**Comment by kylemh** [comment]
I only have tiny critiques! I'm okay ditching left-aligned columns if it makes this easier to maintain. That being said, I'd like for the mobile font size to be larger and have a larger gap so that it's difficult to hit the wrong item with fingers. I'd also like there to be extensive bottom padding so that if people drag on the bottom (or scroll past the bottom on Safari), there's no white space (as seen in photo)
IMG_8621

**Comment by michaelDragomir** [comment]
@kylemh  updated..let me know. :)

**Review by kylemh — APPROVED** [review]

**Comment by kylemh** [comment]
love it! ty

**Pull request merged**
