### PR TITLE
Style tweaks on resources

### PR DESCRIPTION
**Pull request by kylemh**
# Description of changes

- Adjust algolia notice a bit
- Re-activate upvote/downvote buttons with style tweaks
- Adjust margins and alignments for searching form
- Improve accessibility on resource feature

### CODE REVIEW

**Comment by kylemh** [comment]
#### 📝Changed routes:


| [**/resources/\[page\]**](https://operation-code-git-style-tweaks-on-resources.operation-code.now.sh/resources/[page]) | [**/styles/resources.module**](https://operation-code-git-style-tweaks-on-resources.operation-code.now.sh/styles/resources.module) |
|:-:|:-:|
|<a href="https://operation-code-git-style-tweaks-on-resources.operation-code.now.sh/resources/[page]">Screenshot of /resources/[page]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/ZAFJa0S36b3O_NkFwnE_Nra3uU4_.png">(view full size)</a> |<a href="https://operation-code-git-style-tweaks-on-resources.operation-code.now.sh/styles/resources.module">Screenshot of /styles/resources.module</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/DG2DHsKzBL5Cmb6XwMx7JztKLrM_.png">(view full size)</a> |







Commit a507021ee48a1598ade7bb8b77185575cc3f13d0 (https://operation-code-git-style-tweaks-on-resources.operation-code.now.sh).

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit a507021ee48a1598ade7bb8b77185575cc3f13d0

https://deploy-preview-1139--operation-code-storybook.netlify.app

**Comment by ksmacleod99** [comment]
@kylemh and @aaron-suarez what do we need to do to get this PR ready to merge?

**Comment by aaron-suarez** [comment]
When you click the upvote/downvote buttons and you're not logged in, you should be prompted to log in somehow. I'm thinking a slick modal kind of like what StackOverflow does when you try to upvote a question. But right now, it seems if you're not logged in it just does nothing

**Comment by kylemh** [comment]
I’ll follow up with ^ on a different PR

**Pull request merged**
