### PR TITLE
Enable Slack app integration notifications

### PR DESCRIPTION
**Pull request by kylemh**
# Description of changes
Necessary to enable Travis integration on Slack

### CODE REVIEW

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit 27bcd7495e348ac422f52a8f7808054d191fe141

https://deploy-preview-436--operation-code-storybook.netlify.com

**Comment by wimo7083** [comment]
You're going to want to reset that token and then encrypt in Travis. See pybot repo for example

**Comment by kylemh** [comment]
I got lazy because like... if somebody really wants our travis bot notifications in their Slack team 🤷‍♂️

**Comment by kylemh** [comment]
I've reset it, but will bother with this again later.

**Pull request closed without merging**
