### PR TITLE
Create CODE_OF_CONDUCT_TR.md

### PR DESCRIPTION
**Pull request by aytekk**
Turkish version of CODE_OF_CONDUCT.md

# Description of changes
This PR is Turkish version for Turkish developers

### CODE REVIEW

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit 046abe78f85cb9db5238df70376450f6ea96a773

https://deploy-preview-241--operation-code-storybook.netlify.com

**Comment by kylemh** [comment]
Holy cow - this is so cool!

I don't have any way of verifying this, but thanks so much for your contribution. It means the world to us here at Operation Code.

As a token of our gratitude, please fill out [this form](https://goo.gl/forms/r02wt0pBNhkxYciI3) to receive some stickers and a handwritten "thank you" note. ❤️

**Comment by aytekk** [comment]
hey, i do not have Slack username. how can i join Slack?

26 Eki 2018 Cum 23:36 tarihinde Kyle Holmberg <notifications@github.com>
şunu yazdı:

**Comment by kylemh** [comment]
@aytekk you can get the sticker w/o joining Slack.

If you're interested in joining our Slack team _anyways_ and continuing to help, feel free to register on operationcode.org - you'll receive an invite within 24 hours.

**Pull request merged**
