### PR TITLE
Use correct env for Resources API

### PR DESCRIPTION
**Pull request by kylemh**
# Description of changes
Fixes an oopsie

### CODE REVIEW

**Review by aaron-suarez — APPROVED** [review]

**Comment by aaron-suarez** [comment]
If it's ready for merge go ahead and merge it. I'm gonna leave it in case it hasn't been fully tested yet

**Comment by kylemh** [comment]
@aaron-suarez it looks like the resources DB has `JavaScript` and `Javascript` (at least on dev, maybe on both)? Can we just have `JavaScript`.

**Comment by aaron-suarez** [comment]
Screen Shot 2020-10-11 at 5 21 13 PM
looks like it's already fixed on prod. I'll fix it on staging too

**Comment by aaron-suarez** [comment]
@kylemh should be fixed on staging now. I assumed that's what you meant by "dev" because the [resources.yml](https://github.com/OperationCode/resources_api/blob/main/resources.yml) file has all `JavaScript` so everyone's local environment should be fine

**Comment by aaron-suarez** [comment]
I kicked off the integration tests on CircleCI to find out. We'll see if they pass or fail

**Comment by kylemh** [comment]
Thanks!

**Pull request merged**
