### PR TITLE
Profile items conditionally render

### PR DESCRIPTION
**Pull request by fletcherrippon**
# Description of changes
Are now optional and render conditionally:
- branchOfService
- companyName
- companyRole
- createdAt
- disciplines
- employmentStatus
- isMentor
- militaryStatus
- programmingLanguages
# Issue Resolved
[Conditionally render items in profile page #1269](https://github.com/OperationCode/front-end/issues/1269)

### CODE REVIEW

**Review by kylemh — APPROVED** [review]
Thanks so much for your 🎃 Hacktoberfest🎃&nbsp; contribution!

If you weren't aware, we're offering prizes too! You can read about the details [here](https://github.com/OperationCode/START_HERE#-hacktoberfest-).

Regardless, you've contributed, and we recommend you set yourself a reminder to submit the aforementioned form after November 1st (or after you meet all the criteria).

**Comment by kylemh** [comment]
@fletcherrippon - it looks like you'll need to run `yarn lint:scripts`, but I'm curious about your setup... We have a lint fixer setup as part of a "pre-commit" git hook. Did you perhaps run `git commit -m "Profile items conditionally render" --no-verify`? If not, I need to figure out what's unique about your environment so I can help make this repo easier to contribute to for everybody!

**Comment by fletcherrippon** [comment]
@kylemh  Yes I ran `git commit -m "Profile items conditionally render" --no-verify`

**Comment by kylemh** [comment]
Ah! You trickster you. I recommend in the future not avoiding git hooks! You'll have to fix the lint errors and then we'll be good to merge.

**Comment by fletcherrippon** [comment]
I just ran the linter and it's telling me to set defaults for the optional props should I just set the defaults as `''` for types of strings and `false` for types of boolean?

**Comment by kylemh** [comment]
`undefined` works for me!

**Comment by fletcherrippon** [comment]
Just added the default props to `Profile`

**Pull request merged**
