### PR TITLE
Added team page

### PR DESCRIPTION
**Pull request by cmgonzales**
# Description of changes

# Issue Resolved

Fixes #

### CODE REVIEW

**Comment by cmgonzales** [comment]
This is the team page

**Comment by kylemh** [comment]
It looks like you've got tons of merge conflicts within the files changed.

[Check this out](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/), you're gonna need it!

**Comment by kylemh** [comment]
@cmgonzales did you want to a schedule a time where we can walk thru this?

**Comment by cmgonzales** [comment]
@kylemh sure let me know what time youre available

**Comment by kylemh** [comment]
I'll message you on Slack

**Pull request closed without merging**
