### PR TITLE
GitHub integration

### PR DESCRIPTION
**Pull request by chrisgalvan**
Setup GitHub as login provider.

Fixes: #890 #614 

**What was missing?**
- I set the redirectUri as empty and I can see the authorization from GitHub
- Handle the token in the onSuccess method

Auth using GitHub
image

**Important**
GitHub will only redirect back to urls that match with the urls that are in the oauth apps. So this might be a problem testing in staging since the host is different e.g. `https://operation-code-git-fork-chrisgalvan-github-integration.operation-code.now.sh/`

**Pending:**
- [] Error calling backend

 Details:
500 Error calling `https://api.staging.operationcode.org/auth/social/github/` with `accessToken`

```
curl 'https://api.staging.operationcode.org/auth/social/github/' -H 'Accept: application/json, text/plain, */*' --compressed -H 'Content-Type: application/json;charset=utf-8' -H 'Origin: http://localtest.me:3000' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: http://localtest.me:3000/login' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data '{"accessToken":"50d4720d6a23451e44b4"}'
```

Response:
image

### CODE REVIEW

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit 1de2b541a6c87ce46895a242dd68288cd49e5186

https://deploy-preview-891--operation-code-storybook.netlify.com

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit 2e4fc78b74bcb307ea6a5ecff279afcff8353635

https://deploy-preview-891--operation-code-storybook.netlify.com

**Comment by chrisgalvan** [comment]
hey @kylemh do you know why deployment failed?

**Comment by chrisgalvan** [comment]
Ok, I think I got all the files back. The revert removed the files I had previously added.

**Comment by chrisgalvan** [comment]
Hey @kylemh if you want to test the integration in stage (using the url in now) you can change the authorization callback url in the oauth app to `https://operation-code-aqb8wtudt.now.sh/login`

image

Then it should redirect appropiately, (in stage).

After is validated, and want to push to prod you need to update the url again to `https://operationcode.org/login` so it works in prod.

**Comment by kylemh** [comment]
I tried that and got a view similar to the one you posted in OP, but once I clicked authorize the window changed to Facebook and said I had an error logging in.

**Comment by kylemh** [comment]
So we're actually thinking about ditching authentication as part of website entirely and leveraging the Slack API as a means of authentication. Going to close this because of inactivity and the above reason.

**Pull request closed without merging**
