### PR TITLE
refactor: de-structure Proptypes imports to convert PropType imports to named

### LINKED ISSUE #479: Convert PropType imports to named
# Feature request
**Is your feature request related to a problem? Please describe.**
`import PropTypes from 'prop-types';` has a worse developer experience than `import { specificPropType } from 'prop-types';`. For one, it's extra/unnecessary characters. Secondly, `.isRequired` only appears in intellisense when destructuring.

**Describe the solution you'd like**
Convert every `import PropTypes from 'prop-types';` to `import { propTypesUsed } from 'prop-types';` across all files.

### PR DESCRIPTION
**Pull request by Shobhit1**
# Description of changes
This PR is for the feature request #479 . 
de-structure the Proptypes imports into the proptypes that are actually used in the component.

# Issue Resolved

Fixes #479 

## Screenshots/GIFs
Not applicable.

### CODE REVIEW

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit 757f3dfba09d60655857594fdf70df7afadce2e1

https://deploy-preview-480--operation-code-storybook.netlify.com

**Comment by kylemh** [comment]
@Shobhit1 it looks like you've also re-ordered the imports. Can you undo that change?

**Comment by Shobhit1** [comment]
Yes. I will do that. It was my vscode’s organize imports setting on file save. Sorry about that. Will fix that.

**Comment by kylemh** [comment]
I figured it was either that or a global `.eslintrc` config.

No worries at all!

**Comment by Shobhit1** [comment]
@kylemh done. let me know if you find anything that needs fixing in this PR.

**Pull request merged**
