### PR TITLE
added GitHub logo

### PR DESCRIPTION
**Pull request by rusye**
# Description of changes
**What:** Added GitHub link to footer
**Why:** When I went to the site and wanted to access the GitHub repo for the project I couldn't locate it anywhere and had to Google my way to the GitHub repo
**Help:** The logo needs the styling updated to look like the other social links

# Issue Resolved
Fixes nothing at the moment

## Screenshots/GIFs
Before 
operationCodeFooterBefore
After
operationCodeFooterAfter

### CODE REVIEW

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit 07dcf27de60f1db1643da488557df9d6cb3d5ab6

https://deploy-preview-843--operation-code-storybook.netlify.com

**Comment by kylemh** [comment]
I’ll get the right image asset and merge this in

**Comment by kylemh** [comment]
Can you add this icon as `github_logo_circle` and use it instead?

```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 438.5 438.5">
  <title>GitHub Logo</title>
  <path d="M409 115a218 218 0 00-300-80 218 218 0 00-67 319c28 38 64 64 108 79 5 1 9 0 11-2 3-3 4-5 4-9a6590 6590 0 000-41l-7 2-16 1-20-2c-6-2-13-5-19-9-6-5-10-10-12-18l-3-6-9-15c-4-5-8-9-12-11l-2-1a21 21 0 01-7-7c0-2 0-3 2-4l8-1 6 1 14 7c5 4 10 8 14 15s9 13 15 17c7 4 13 7 19 7l16-2 13-4c2-13 7-23 14-30-11-1-20-2-29-5-9-2-18-6-27-11a77 77 0 01-38-49c-4-12-6-27-6-43 0-23 8-42 23-59-7-17-6-36 2-58 5-2 14 0 24 4a172 172 0 0136 19 202 202 0 01110 0l11-7c7-5 16-9 26-13s18-5 23-3c9 22 10 41 3 58 15 17 22 36 22 59 0 16-2 31-6 43-4 13-9 23-15 30-6 8-14 14-23 19s-18 9-27 11c-8 3-18 4-29 5 10 9 15 22 15 41v60c0 4 1 6 3 9 3 2 7 3 12 2 44-15 80-41 108-79 28-39 42-82 42-129 0-40-10-77-30-110z"/>
</svg>
```

**Comment by rusye** [comment]
I tried copying that SVG html code and pasting it into a text editor but when I do `yarn build` it fails to compile.  Do you have any tips regarding that?  Going to see if I could have a friend with access to Adobe drop me the whole file.

**Comment by kylemh** [comment]
Where did you put the file? It needs to be at `static/images/icons/github_logo_circle.svg`

**Comment by rusye** [comment]
It is in the correct folder.  There is something wrong with the `<path d="some stuff" />`, if I copy-paste the twitter `<path d="some stuff" />` it builds just fine.  I'm going to see if I could find something online for it.

**Comment by kylemh** [comment]
Try again. I edited it cuz there was a missing empty space near the end

**Comment by kylemh** [comment]
whoops - sorry for that

**Comment by rusye** [comment]
Np, at least I was able to figure out the issue.  Do you think we should include that circle on the outside or will do just fine?  Just wanting it to look like the other ones.

**Comment by rusye** [comment]
Any thoughts as to why that Cypress test is failing?  I'm not familiar with Cypress but I wasn't able to get the test to work on my local computer either when I do `yarn test` it passes all of those but if I do `yarn test:e2e:headless` I get this error message even though I didn't touch those tests `Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'when server responds succes...'`

**Comment by kylemh** [comment]
See #851 for context on flakey Cypress errors.

**Pull request merged**
