### PR TITLE
Fix pagination on /resources

### PR DESCRIPTION
**Pull request by kylemh**
# Description of changes
- 🥴 Fixed typos on /resources related API functions
- 🚧 Improved Pagination and PaginationItem component APIs
- ♺ Integrated dynamic routing for /resources
- ✅ Working pagination

### CODE REVIEW

**Comment by kylemh** [comment]
#### 📝Changed routes:


| [**/resources/\[page\]**](https://operation-code-git-resources-page.operation-code.now.sh/resources/[page]) |
|:-:|
|<a href="https://operation-code-git-resources-page.operation-code.now.sh/resources/[page]">Screenshot of /resources/[page]</a><br /><sup><a href="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/FJJwvUoZ8WTEkjkfO8i0oHX5hk0_">(view full size)</a> |







Commit 0966d438e19b15fa8aecb92326316c6314715b0b (https://operation-code-git-resources-page.operation-code.now.sh).

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit 0966d438e19b15fa8aecb92326316c6314715b0b

https://deploy-preview-1027--operation-code-storybook.netlify.com

**Comment by aaron-suarez** [comment]
@kylemh do you think we need to worry about any of the CI failures or is it good to merge?

**Comment by kylemh** [comment]
Good to merge. Just no coverage on the page yet. That’s fine since it’s not live yet.

**Pull request merged**
