### PR TITLE
Adds sort-import to eslint

### LINKED ISSUE #200: Integrate import sorting in eslint config
# Feature
## Why is this feature being added?

I'd like imports to be sorted in a uniform manner, so that it doesn't become an aspect of code reviews.

## What should your feature do?
Use https://eslint.org/docs/rules/sort-imports and implement rules that would yield the following result:

```javascript
import Default from 'some-lib-in-node_modules';
import { Module } from 'some-lib-in-node_modules';
import Default from 'resolved-module/folder/path';
import { Module } from 'resolved-module/folder/path';
import Default from '../relative/path';
import { Module } from '../relative/path';
```

with alphabetically sorted modules and imports.

After completion, please run `yarn format` and commit any file changes.

### PR DESCRIPTION
**Pull request by chrislaughlin**
# Description of changes
Adds sort-imports eslint rule 

# Issue Resolved

Fixes #200

### CODE REVIEW

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit f6146ec7c74d23c4bcbf207be45ff229b6842610

https://deploy-preview-202--operation-code-storybook.netlify.com

**Comment by kylemh** [comment]
@chrislaughlin note that in the issue I recommend using `yarn format` locally. Can you do that instead of changing the lint command?

**Comment by chrislaughlin** [comment]
ah yeah ill run that and update the code thanks

**Comment by dirtyredz** [comment]
someone beat me to it lol

**Comment by kylemh** [comment]
@chrislaughlin I realize now that I led you astray. The `sort-imports` rule was a bludgeon for alphabetization 🤢 


Instead I used [eslint-plugin-imports](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) order rule to get the linting I desired.

I've committed to this branch and will push now. Thanks for helping!

**Comment by kylemh** [comment]
@chrislaughlin no worries - glad I dove in cuz that `--fix` was like 😱

**Pull request merged**
