### PR TITLE
fix join form password field validation flash message

### PR DESCRIPTION
**Pull request by thecodestuff**
# Description of changes
When user provide password which is not valid that is password is either in lower case or numbers etc a flash message display along side password field which is not displaying  correctly . So by tweaking a css little bit , not its displaying flash message nicely .(see screenshots below).

# Issue Resolved
This PR made against issue #1033  

## Screenshots
before fix screenshot 
Screenshot from 2020-01-26 12-05-27

after fix screenshot
Screenshot from 2020-01-26 11-50-57

### CODE REVIEW

**Comment by kylemh** [comment]
This solution won't work well if content for the alerts gets any larger, but I think this is a good enough solution for now! Sorry about the CD check failures... They'll be fixed soon, and then I'll merge!

**Comment by thecodestuff** [comment]
@kylemh , So did I need to change something to be able to clear these CI/CD checks or they get clear automatically ?

**Comment by kylemh** [comment]
I’ll have it cleared once I figure out the issue. I’ve asked Zeit for some help. It just started a few days ago.

If you just leave it alone, it’ll get merged!

**Comment by kylemh** [comment]
🤖 **This is a bot** 🤖<br /><br />🎉 Deployed Storybook preview! 🎉<br /><br />Click the link at the bottom of this comment to see it live.

Built with commit dd26d24c493c3695f3a0305ac1591732ff889570

https://deploy-preview-1034--operation-code-storybook.netlify.com

**Pull request merged**
